/*
 * Copyright 2016-2020 Luca Zanconato
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef SALTPACK_MESSAGEWRITER_H
#define SALTPACK_MESSAGEWRITER_H

#include <list>
#include "Base.h"

namespace saltpack {

    /**
     *  @brief The class used to encrypt or sign a message.
     *
     *  Use it in conjunction with ArmoredOutputStream to produce armored BaseX output.
     */
    class MessageWriter : public Base {

    public:
        /**
         * Creates a new MessageWriter instance to encrypt a message.
         *
         * @param os the destination output stream that will contain the encrypted data.
         * @param senderSecretkey the private key of the sender, generated by Utils::generateKeypair().
         * @param recipients the list of public keys of the recipients.
         * @param visibleRecipients if true, the public keys of the recipients will be visible in the encrypted message.
         *
         * @throws SaltpackException
         */
        MessageWriter(std::ostream &os, BYTE_ARRAY senderSecretkey, const std::list<BYTE_ARRAY>& recipients,
                      bool visibleRecipients);

        /**
         * Creates a new MessageWriter instance to encrypt a message.
         * The recipients public keys will be visible in the encrypted message.
         *
         * @param os the destination output stream that will contain the encrypted data.
         * @param senderSecretkey the private key of the sender, generated by Utils::generateKeypair().
         * @param recipients the list of public keys of the recipients.
         *
         * @throws SaltpackException
         */
        MessageWriter(std::ostream &os, BYTE_ARRAY senderSecretkey, const std::list<BYTE_ARRAY>& recipients);

        /**
         * Creates a new MessageWriter instance to encrypt a message remaining anonymous.
         *
         * @param os the destination output stream that will contain the encrypted data.
         * @param recipients the list of public keys of the recipients.
         * @param visibleRecipients if true, the public keys of the recipients will be visible in the encrypted message.
         *
         * @throws SaltpackException
         */
        MessageWriter(std::ostream &os, const std::list<BYTE_ARRAY>& recipients, bool visibleRecipients);

        /**
         * Creates a new MessageWriter instance to encrypt a message remaining anonymous.
         * The recipients public keys will be visible in the encrypted message.
         *
         * @param os the destination output stream that will contain the encrypted data.
         * @param recipients the list of public keys of the recipients.
         *
         * @throws SaltpackException
         */
        MessageWriter(std::ostream &os, const std::list<BYTE_ARRAY>& recipients);

        /**
         * Creates a new MessageWriter instance to sign a message.
         *
         * @param os the destination output stream that will contain the signed data.
         * @param senderSecretkey the private key of the sender, generated by Utils::generateSignKeypair().
         * @param detatchedSignature attached/detached signature flag.
         *
         * @throws SaltpackException
         */
        MessageWriter(std::ostream &os, const BYTE_ARRAY& senderSecretkey, bool detatchedSignature);

        /**
         * Creates a new MessageWriter instance to signcrypt a message.
         *
         * @param os the destination output stream that will contain the signcrypted data.
         * @param senderSecretkey the private key of the sender, generated by Utils::generateSignKeypair().
         * @param recipientsPublickeys the list of Curve25519 public keys of the recipients.
         *        The list can be empty.
         * @param symmetricKeys the list of symmetric keys of the recipients: the first array is treated as the
         *        identifier, the second as the key itself. The list can be empty.
         *
         * @throws SaltpackException
         */
        MessageWriter(std::ostream &os, const BYTE_ARRAY& senderSecretkey, const std::list<BYTE_ARRAY>& recipientsPublickeys,
                      const std::list<std::pair<BYTE_ARRAY, BYTE_ARRAY>>& symmetricKeys);

        /**
         * Creates a new MessageWriter instance to signcrypt a message remaining anonymous.
         *
         * @param os the destination output stream that will contain the signcrypted data.
         * @param recipientsPublickeys the list of Curve25519 public keys of the recipients.
         *        The list can be empty.
         * @param symmetricKeys the list of symmetric keys of the recipients: the first array is treated as the
         *        identifier, the second as the key itself.
         *        The list can be empty.
         *
         * @throws SaltpackException
         */
        MessageWriter(std::ostream &os, const std::list<BYTE_ARRAY>& recipientsPublickeys,
                      const std::list<std::pair<BYTE_ARRAY, BYTE_ARRAY>>& symmetricKeys);

        /**
         * Desctructor. Securely deletes the allocated buffers using `sodium_memzero`.
         */
        ~MessageWriter() override;

        /**
         * Adds a block to the current message.
         *
         * @param data the data for the block, maximum 1MB.
         * @param final the flag defining the last packet of the message.
         *
         * @throws SaltpackException
         */
        void addBlock(BYTE_ARRAY data, bool final);

    private:
        std::ostream &output;
        unsigned long packetIndex;
        BYTE_ARRAY payloadKey;
        BYTE_ARRAY headerHash;
        std::list<BYTE_ARRAY> macKeys;
        bool lastBlockAdded;

        BYTE_ARRAY secretKey;
        BYTE_ARRAY buffer;

        std::string generateEncryptionHeader(BYTE_ARRAY ephemeralSecretkey, BYTE_ARRAY ephemeralPublickey,
                                             BYTE_ARRAY senderPublickey, const std::list<BYTE_ARRAY>& recipientsPublickeys,
                                             bool visibleRecipients);

        static std::string generateSignatureHeader(BYTE_ARRAY senderPublickey, bool detatchedSignature);

        std::string generateSigncryptionHeader(const BYTE_ARRAY& ephemeralSecretkey, const BYTE_ARRAY& ephemeralPublickey,
                                               BYTE_ARRAY senderPublickey, const std::list<BYTE_ARRAY>& recipientsPublickeys,
                                               const std::list<std::pair<BYTE_ARRAY, BYTE_ARRAY>>& symmetricKeys);

        static std::string encodeHeader(const std::string& header);

        static BYTE_ARRAY generateAuthenticator(BYTE_ARRAY concat, BYTE_ARRAY recipientMacKey);

        std::string generatePayloadPacket(BYTE_ARRAY message, bool final);

        std::string generateSignaturePayloadPacket(const BYTE_ARRAY& message, bool final);

        std::string generateSigncryptionPayloadPacket(BYTE_ARRAY message, bool final);
    };
}

#endif //SALTPACK_MESSAGEWRITER_H
