language: cpp

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: osx
      osx_image: xcode7.3
      compiler: clang

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then eval "${MATRIX_EVAL}"; fi

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get update && sudo apt-get -y install libgmp-dev lcov; fi

  - if [ $TRAVIS_OS_NAME = linux ]; then wget https://github.com/msgpack/msgpack-c/releases/download/cpp-2.0.0/msgpack-2.0.0.tar.gz; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then tar -xvzf msgpack-2.0.0.tar.gz; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then pushd msgpack-2.0.0 && cmake . && make && sudo make install && popd; fi

  - if [ $TRAVIS_OS_NAME = linux ]; then wget https://github.com/jedisct1/libsodium/releases/download/1.0.9/libsodium-1.0.9.tar.gz; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then tar -xvzf libsodium-1.0.9.tar.gz; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then pushd libsodium-1.0.9 && ./configure && make && sudo make install && popd; fi

  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then if ! brew ls --version libsodium &>/dev/null; then brew install libsodium; fi; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then if ! brew ls --version msgpack &>/dev/null; then brew install msgpack; fi; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then if ! brew ls --version gmp &>/dev/null; then brew install gmp; fi; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then if ! brew ls --version lcov &>/dev/null; then brew install lcov; fi; fi

  - gem install coveralls-lcov

script:
 - mkdir build
 - cd build
 - cmake .. -DENABLE_COVERAGE=true -DCMAKE_BUILD_TYPE=Debug && make && make saltpack-coverage
 - coveralls-lcov coverage.info.cleaned