---
name: build

on: [push]

jobs:
  linux:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Dependencies
        run: |
          sudo apt-get install -y build-essential wget cmake python3-pip libsodium-dev libmsgpack-dev
          sudo pip install gcovr==7.2

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DENABLE_COVERAGE=true -DCMAKE_BUILD_TYPE=Debug
          make
          make saltpack-coverage-xml

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: build/saltpack-coverage-xml.xml
          github-token: ${{ secrets.GITHUB_TOKEN }}

  macos:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Dependencies
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
        run: brew install libsodium msgpack msgpack-cxx

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
          ./saltpack-test
